var tl = new TimelineMax({repeat: -1, yoyo: true});
var speed = 0.3;
tl.to("#two", 0, {right: "0px", left: "unset", width: "40px"})
  .to("#three", speed, {left: "0px", right: "unset", width: "40px"})
  .to("#two", speed, {height: "100px"})
  .to("#two", speed, {bottom: "0px", height: "40px", top: "unset"})
  .to("#one", speed, {width: "100px"})
  .to("#one", speed, {right: "0px", left: "unset", width: "40px"})
  .to("#three", speed, {bottom: "0px", top: "unset", height: "100px"})
  .to("#three", speed, {top: "0px", bottom: "unset", height: "40px"})
  .to("#two", speed, {width: "100px"})
  .to("#two", speed, {left: "0px", right: "unset", width: "40px"})
  .to("#one", speed, {height: "100px"})
  .to("#one", speed, {bottom: "0px", height: "40px", top: "unset"})
  .to("#three", speed, {width: "100px"})
  .to("#three", speed, {right: "0px", left: "unset", width: "40px"})
  .to("#two", speed, {height: "100px"})
  .to("#two", speed, {top: "0px", height: "40px", bottom: "unset"})
  .to("#one", speed, {width: "100px"})
  .to("#one", speed, {left: "0px", right: "unset", width: "40px"})
  .to("#three", speed, {height: "100px"})
  .to("#three", speed, {bottom: "0px", height: "40px", top: "unset"})
  .to("#two", speed, {width: "100px"})
  .to("#two", speed, {right: "0px", left: "unset", width: "40px"})
  .to("#one", speed, {height: "100px"})
  .to("#one", speed, {top: "0px", height: "40px", bottom: "unset"})
  .to("#three", speed, {width: "100px"});